---

- hosts: all
  become: true
  tasks:
  
  - name: install apache2 & vim-nox packages for Ubuntu
    apt:
      name: 
      - apache2
      - vim-nox
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
 
  - name: install apache & vim-nox packages for centos
    dnf:
      name: 
      - httpd
      - vim-nox
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"