- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
       upgrade: dist
       update_cache: yes 

- hosts: webservers
  become: true
  tasks:

  - name: install apache2 package (Ubuntu)
    tags: apache2
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: absent 

- hosts: db
  become: true
  tasks:

  - name: install mariadb server
    tags: db
    apt:
       name: mariadb
       state: absent
