- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
       upgrade: dist
       update_cache: yes

- hosts: webservers
  become: true
  tasks:

  - name: install apache2 package (Ubuntu)
    tags: apache2
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent

  - name: copy html file for site
    tags: file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.0-alpha20240501/terraform_1.9.0-alpha20240501_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    state: absent
